//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesDBAndCRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Movy
    {
        [Required]
        public int ID { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
        [StringLength(200)]
        public string Director { get; set; }

        [Required]
        public Nullable<int> Year { get; set; }

        [Required]
        [StringLength(200)]
        public string LeadingMaleRole { get; set; }

        [Required]
        [Range(1, 100)]
        public Nullable<int> LeadingMaleRoleAge { get; set; }

        [StringLength(100)]
        public string LeadingMaleRoleAgeStudio { get; set; }

        [StringLength(500)]
        public string LeadingMaleRoleAgeStudioAddress { get; set; }

        [Required]
        [StringLength(200)]
        public string LeadingFemaleRole { get; set; }

        [Required]
        [Range(1, 100)]
        public Nullable<int> LeadingFemaleRoleAge { get; set; }

        [StringLength(100)]
        public string LeadingFemaleRoleStudio { get; set; }

        [StringLength(500)]
        public string LeadingFemaleRoleStudioAddress { get; set; }
    }
}
